config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  resources :years
  root 'contest#index'
  resources :contest, only: [:show]
  resources :creators, only: [:show]
  get 'upload', to: 'contest#upload'
  post 'upload', to: 'contest#uploadpost'
  
  if ENV['WEBSIDEKIQ'] == "TRUE"
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '/numerics' do
    get 'totalphotos', to: 'numerics#totalphotos'
    get 'todayphotos', to: 'numerics#todayphotos'
    get 'totalcreators', to: 'numerics#totalcreators'
    get 'totalcreatorsapposta', to: 'numerics#totalcreatorsapposta'
    get 'todaycreatorsapposta', to: 'numerics#todaycreatorsapposta'
    get 'days', to: 'numerics#days'
    get 'photograph', to: 'numerics#photograph'
    get 'photoday', to: 'numerics#photoday'
    get 'usedonwiki', to: 'numerics#usedonwiki'
    get 'usedonwikipercentage', to: 'numerics#usedonwikipercentage'
    get 'iscrittiappostapercentage', to: 'numerics#iscrittiappostapercentage'
    get 'miglioriutenti', to: 'numerics#miglioriutenti'
    get 'iscrittiappostagraph', to: "numerics#iscrittiappostagraph"
    get 'photos_relativetogeneral', to: "numerics#photos_relativetogeneral"
    get 'participants_relativetogeneral', to: "numerics#participants_relativetogeneral"
    get 'special_photos', to: "numerics#special_photos"
    get 'new_monuments', to: "numerics#new_monuments"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contest.rb
class Contest < ApplicationRecord
  has_many :photos
  has_one_attached :logo
  has_many :contest_years
  validate :correct_document_mime_type

  #def position(year_obj)
  #  return ContestYear.where(year: year_obj).sort_by{|c| c.count}.pluck(:id).reverse.find_index(self.id) + 1
  #end

  def cat_name(year_obj)
    return "#{ENV["CAT_PREFIX"]} #{year_obj.year} #{ENV["CAT_SUFFIX"]} - #{self.category}"
  end

  def correct_document_mime_type
    if logo.attached? && !logo.image?
      document.purge # delete the uploaded file
      errors.add(:logo, 'Deve essere una immagine')
    end
  end
end

app/controllers/contest_controller.rb
class ContestController < ApplicationController
  include ContestHelper
  http_basic_authenticate_with name: "wikilovesmonuments", password: ENV["SECRET_PASSWORD"], only: [:upload, :uploadpost]

  def index
    @contests = Contest.with_attached_logo.includes(:photos, :contest_years).sort_by{ |contest| contest.contest_years.where(year: @year).first&.count }.reverse
    @nophotograph = {}
    Nophoto.where(regione: nil).each do |nop|
      @nophotograph[nop.created_at] = nop.count
    end

    @nophotographpercent = {}
    Nophoto.where(regione: nil).each do |nop|
      @nophotographpercent[nop.created_at] = nop.percent
    end
    @rank = ContestYear.where(year: @year).sort_by{|c| c.count}.pluck(:id).reverse
  end

  def show
    @contest = Contest.includes(:photos => :creator).find(params[:id])

    @photos = @contest.photos.select { |photo| photo.year == @year }
    @creators = @photos.map(&:creator).uniq.sort_by { |c| c.photos.select { |p| p.contest == @contest && p.year == @year }.count }
    @contestyear = ContestYear.find_by(contest: @contest, year: @year)
    ## Ordinamento dei creatori

    @creators = @creators.sort_by{|gp| gp.photos.where(contest: @contest).count}.reverse
    @nophotograph = {}
    Nophoto.where(regione: @contest.region, year: @year).each do |nop|
      @nophotograph[nop.created_at] = nop.count
    end

    @nophotographpercent = {}
    Nophoto.where(regione: @contest.region, year: @year).each do |nop|
      @nophotographpercent[nop.created_at] = nop.percent
    end

  end

  def upload
    unless (@contest = Contest.find_by(id: params[:id]))
      redirect_to root_path
      flash[:error] = 'ID NON VALIDO'
    end
  end

  def uploadpost
    @contest = Contest.find_by(id: params[:contest][:id])
    if @contest.update!(params_ok)
      redirect_to root_path
      flash[:success] = 'OK'
    else
      render 'upload'
    end
  end
end
private
def params_ok
  params.require(:contest).permit(:logo)
end

app/helpers/contest_helper.rb
module ContestHelper
  def percentage_of(n)
    self.to_f / n.to_f * 100.0
  end
end

app/views/contest/data.html.erb
<%= provide(:title, 'Aggiornamento dati...') %>
OK

app/views/contest/index.html.erb
<%= provide(:title, "Statistiche concorso WLM") %>
<h1 class="title"><%= ENV["TITLE"] %> <%= @year&.year %></h1>
<h2 class="subtitle">Le statistiche dei concorsi regionali</h2>
<table id="elenco-concorsi">
    <thead>
        <th>Pos.</th>
        <th>Nome del concorso</th>
        <th>Foto caricate</th>
        <th>%/t</th>
        <% if @year.special %>
        <th><%=@year.special_category_label %></th>
        <th>%/t</th>
        <th>%</th>
        <% end %>
        <th>Foto usate (ns0)</th>
        <th>%</th>
        <th>Utenti partecipanti</th>
        <th>%/t</th>
        <th>Utenti iscritti <br />per WLM</th>
        <th>%</th>
        <th>Monumenti partecipanti</th>
        <th>Monumenti senza foto</th>
        <th>%</th>
        <th>Monumenti ritratti</th>
        <th>%</th>
        <th>Nuovi monumenti</th>
        <th>%</th>
        <th>Links</th>
    </thead>
    <tbody>
        <% @contests.reverse.each do |contest| %>
        <% contestyear = ContestYear.find_by(year: @year, contest: contest) %>
        <% next if contestyear.nil? # Significa che non è stato ancora processato per l'anno %>
        <tr>
            <th><%= @rank.find_index(contestyear.id) + 1 %></th>
            <td><%= link_to contest.name, contest %></td>
            <td><%= contestyear.count %></td>
            <td><%= contestyear.percent_of_total&.truncate(1) %></td>
            <!-- Sezione concorso speciale -->
        <% if @year.special %>
            <td><%= contestyear.special_category_count %></td>
            <td><%= contestyear.special_category_percent_of_total&.truncate(1) %></td>
            <td><%= (contestyear.special_category_count.to_f / contestyear.count.to_f * 100.0).truncate(1) unless (contestyear.special_category_count.to_f / contestyear.count.to_f * 100.0).nan? %></td>
        <% end %>
            <!-- Fine sezione concorso speciale -->
            <td><%= contestyear.usedonwiki %></td>
            <td><%= contestyear.usedonwiki_percentage&.truncate(1) %></td>
            <!-- Conto degli utenti partecipanti -->
            <td><%= contestyear.creators %></td>
            <td><%= contestyear.participants_percent_of_total&.truncate(1) %></td>
            <td><%= contestyear.creatorsapposta.to_i %> </td>
            <td><%= (contestyear.creatorsapposta.to_f / contestyear.creators.to_f * 100.0)&.truncate(1) unless contestyear.creators == 0 %> <%= '0.0' if contestyear.creators == 0%></td>
            <td><%= contestyear.monuments %></td>
            <td><%= contestyear.nophoto %></td>
            <td><%= (contestyear.nophoto.to_f / contestyear.monuments.to_f * 100.0)&.truncate(1) unless contestyear.monuments == 0 %> <%= '0.0' if contestyear.monuments == 0%></td>
            <td><%= contestyear.depicted_monuments %></td>
            <td><%= contestyear.depicted_monuments_percentage&.truncate(1) %></td>
            <td><%= contestyear.new_monuments %></td>
            <td><%= contestyear.new_monuments_percentage&.truncate(1) %></td>   
            <td><%= link_to 'Grafico, statistiche e classifica', contest, class: 'button is-link', id: contest.id %>

        </tr>
        <% end %>
    </tbody>
</table>
<% @contests.each do |contest| %>
<% contestyear = ContestYear.find_by(year: @year, contest: contest) %>
<% next if contestyear.nil? # Significa che non è stato ancora processato per l'anno %>
<% if contestyear.count == 0 %>
<!-- Contest stats don't work for empty contests -->
<script>
    document.getElementById('<%= contest.id%>').setAttribute('disabled', 'wlm-zeroelements');

    document.getElementById('<%= contest.id%>').addEventListener('click', function(event) {
        event.preventDefault();
    });
</script>
<% end %>
<% end %>
<br />
<%= link_to 'Trova i monumenti WLM vicino a te', 'https://app.wikilovesmonuments.it', class: 'button is-danger' %>

<br />
<h1 class="subtitle">Pagina personale di un utente</h1>
<div class="control">
    <input class="input" name="id" type="text" id="username">
</div>
<br />
<div class="control">
    <a class="button is-primary is-small" id="username-submit">Invia</a>
</div>

<script>
    $('#username-submit').click(function() {
        var link = 'https://' + location.hostname + '/creators/' + $('#username').val();
        $('#username-submit').attr('href', link);
    });
</script>
<script>
    $('#elenco-concorsi').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });
</script>

<br />

<% if Nophoto.where(regione: nil, year: @year).count > 0 %>
    <h2 class="subtitle">Grafico monumenti senza foto</h2>
    <%= line_chart @nophotograph, xmin:  "#{DateTime.now.strftime('%Y')}-08-31", xmax:  "#{DateTime.now.strftime('%Y')}-09-30"%>
    <h2 class="title is-5">Grafico percentuale</h2>
    <%= line_chart @nophotographpercent, xmin:  "#{DateTime.now.strftime('%Y')}-08-31", xmax:  "#{DateTime.now.strftime('%Y')}-09-30"%>

    <% a = Nophoto.where(regione: nil).last.monuments %>
    <% b = Nophoto.where(regione: nil).last.count %>
    <p><b>Monumenti totali partecipanti</b>: <%= Nophoto.where(regione: nil, year: @year).last.monuments %>
    <p><b>Monumenti senza foto oggi</b>: <%= Nophoto.where(regione: nil, year: @year).last.count %> (<%= (b.to_f / a.to_f * 100.0).truncate(1) unless (b.to_f / a.to_f * 100.0).nan? || b == 0 || a == 0 %> <%= '0.0' if (b.to_f / a.to_f * 100.0).nan? || b == 0 || a == 0%>%)
    <p><b>Monumenti CON foto oggi</b>: <%= Nophoto.where(regione: nil, year: @year).last.monuments - Nophoto.where(regione: nil, year: @year).last.count %>
    <p><b>Monumenti senza foto prima dell'inizio di WLM</b>: <%= Nophoto.find_by(regione: nil, created_at: Date.parse("01-#{ENV["MONTH"].to_i - 1}-#{@year.year}").end_of_month.midnight...Date.parse("01-#{ENV["MONTH"].to_i - 1}-#{@year.year}").end_of_month.end_of_day)&.count %>  (<%= Nophoto.find_by(regione: nil, created_at: Date.parse("01-#{ENV["MONTH"].to_i - 1}-#{@year.year}").end_of_month.midnight...Date.parse("01-#{ENV["MONTH"].to_i - 1}-#{@year.year}").end_of_month.end_of_day).percent %> %)
    <p><b>Monumenti con una categoria su Commons</b>: <%= Nophoto.where(regione: nil, year: @year).last.with_commons %>
    <p><b>Monumenti con un'immagine su Wikidata</b>: <%= Nophoto.where(regione: nil, year: @year).last.with_image %>
    <p><b>Monumenti con un'immagine su Wikidata o una categoria su Commons ma senza foto partecipanti a WLM</b>: <%= Nophoto.where(regione: nil, year: @year).last.nowlm %>
    <p><b>Fotografie caricate</b>: <%= @year.total %></p>
    <p><b>Fotografie <%= @year.special_category_label %></b>:<%= @year.special_category_total %></p>
    <p><b>Partecipanti</b>: <%= @year.creators_count %></p>
    <p><b>Monumenti rappresentati</b>: <%= @year.depicted_monuments %></p>
    <% if @year.special? %><p><b><%= @year.special_category_label %></b>: <%= @year.special_depicted_monuments %></p><% end %>
    <p><b>Monumenti nuovi</b>: <%= @year.new_monuments %></p>
<% end %>

<div class="buttons">
    <%= link_to "Aiuta a creare le categorie per i monumenti con un'immagine ma sprovvisti di categoria", "https://it.wikipedia.org/wiki/Progetto:Wiki_Loves_Monuments/Manutenzione/Monumenti_con_immagine_senza_categoria", class: 'button is-warning' %>
</div>

app/views/contest/show.html.erb
<%= provide(:title, @contest.name) %>
<%= link_to "Home", root_path, class: "button is-small is-info", data: { turbolinks: false }%>
<% if @contest.logo.attached? %>
<div class="columns">
    <div class="column">
        <%=image_tag @contest.logo.variant(resize_to_limit: [200, 200]) if @contest.logo.attached? %>
    </div>
    <div class="column">
        <% end %>
        <h1 class="title"><%= @contest.name %></h1>
        <% if @contest.logo.attached? %>
    </div>
</div>
<% end %>
<h2 class="subtitle">Il grafico</h2>
<%= line_chart @contest.photos.where(year: @year).group_by_day(:photodate).count, xmin: "#{@year.year}-09-01", xmax: "#{@year.year}-09-30"%>
<br />
<h2 class="subtitle">La classifica degli utenti</h2>

<table class="table is-striped">
    <thead>
        <th>Nome utente</th>
        <th>Foto caricate</th>
        <th>Foto usate su wiki</th>
        <th>Foto di nuovi monumenti</th>
        <th>Data di iscrizione (iscritto per WLM)</th>
    </thead>
    <tbody>
        <% @creators.each do |creator| %>
        <tr>
            <td><%= link_to creator.username, creator %></td>
            <td><%= creator.photos.select{|c| c.contest == @contest && c.year == @year}.count %></td>
            <td><%= creator.photos.select{|c| c.contest == @contest && c.year == @year && c.usedonwiki == true }.count %> (<%= (creator.photos.select{|c| c.contest == @contest && c.usedonwiki == true && c.year == @year}.count.to_f / creator.photos.select{|c| c.contest == @contest && c.year == @year}.count.to_f * 100.0).round(1) %> %)</td>
            <td><%= creator.photos.select{|c| c.contest == @contest && c.new_monument == true && c.year == @year }.count %> (<%= (creator.photos.select{|c| c.contest == @contest && c.new_monument == true && c.year == @year }.count.to_f / creator.photos.select{|c| c.contest == @contest && c.year == @year}.count.to_f * 100.0).round(1) %> %)</td>
            <td><%= creator.creationdate.strftime('%d/%m/%Y') unless creator.creationdate.nil? %> (<%= creator.proveniencecontest == @contest.id ? 'Sì' : 'No' %>)</td>
        </tr>
        <% end %>
    </tbody>
</table>

<div class="buttons is-centered">
    <%= link_to 'Categoria delle foto caricate', "https://commons.wikimedia.org/wiki/#{@contest.cat_name(@year)}", class: 'button is-link is-big' %>
    <%= link_to 'Pagina ufficiale del concorso', @contest.url, class: 'button is-danger is-big' %>
</div>

<br />

<br />
<% if Creator.where(proveniencecontest: @contest.id).count > 0 %>
<h2 class="subtitle">Utenti iscritti appositamente per WLM</h2>
<%= line_chart Creator.where(proveniencecontest: @contest.id).group_by_day(:creationdate).count, xmin:  "#{DateTime.now.strftime('%Y')}-09-01", xmax:  "#{DateTime.now.strftime('%Y')}-09-30"%>
<% end %>

<% if Nophoto.where(regione: @contest.region, year: @year).count > 0 && !@contest.region.nil? %>
<h2 class="subtitle">Grafico monumenti senza foto</h2>
<%= line_chart @nophotograph, xmin:  "#{DateTime.now.strftime('%Y')}-08-31", xmax:  "#{DateTime.now.strftime('%Y')}-09-30"%>
<h2 class="title is-5">Grafico percentuale</h2>
<%= line_chart @nophotographpercent, xmin:  "#{DateTime.now.strftime('%Y')}-08-31", xmax:  "#{DateTime.now.strftime('%Y')}-09-30"%>
<p><b>Monumenti totali partecipanti</b>: <%= Nophoto.where(regione: @contest.region, year: @year).last.monuments %>
<p><b>Monumenti senza foto oggi</b>: <%= Nophoto.where(regione: @contest.region, year: @year).last.count %> (<%= (@contestyear.nophoto.to_f / @contestyear.monuments.to_f * 100.0).truncate(1) unless (@contestyear.nophoto.to_f / @contestyear.monuments.to_f * 100.0).nan? || @contestyear.nophoto == 0 || @contestyear.monuments == 0 %> <%= '0.0' if (@contestyear.nophoto.to_f / @contestyear.monuments.to_f * 100.0).nan? || @contestyear.nophoto == 0 || @contestyear.monuments == 0%>%)
<p><b>Monumenti CON foto oggi</b>: <%= Nophoto.where(regione: @contest.region, year: @year).last.monuments - Nophoto.where(regione: @contest.region, year: @year).last.count %>
<p><b>Monumenti senza foto prima dell'inizio di WLM</b>: <%= Nophoto.find_by(regione: @contest.region, created_at: Date.parse("01-#{ENV["MONTH"].to_i - 1}-#{@year.year}}").end_of_month.midnight...Date.parse("01-#{ENV["MONTH"].to_i - 1}-#{@year.year}").end_of_month.end_of_day).count %> (<% Nophoto.find_by(regione: @contest.region, created_at: Date.parse("01-#{ENV["MONTH"].to_i - 1}-#{@year.year}").end_of_month.midnight...Date.parse("01-#{ENV["MONTH"].to_i - 1}-#{@year.year}").end_of_month.end_of_day).percent %> %)
<p><b>Monumenti con una categoria su Commons</b>: <%= Nophoto.where(regione: @contest.region, year: @year).last.with_commons %>
<p><b>Monumenti con un'immagine su Wikidata</b>: <%= Nophoto.where(regione: @contest.region, year: @year).last.with_image %>
<p><b>Monumenti con un'immagine su Wikidata o una categoria su Commons ma senza foto partecipanti a WLM</b>: <%= Nophoto.where(regione: @contest.region, year: @year).last.nowlm %>
    <% end %>

    <br />
    <br />

    <a id="show-complete" class="button is-small is-info">Mostra dati completi</a>
<div id="complete" class="is-hidden">
    <ul>
        <% @contest.as_json.each do |key, val| %>
        <li><b><%= key %>:</b> <%= val %></li>
        <% end %>
    </ul>

    <ul>
        <% @contest.contest_years.as_json.each do |key, val| %>
        <li><b><%= key %>:</b> <%= val %></li>
        <% end %>
    </ul>

    <ul>
        <% Nophoto.where(regione: @contest.region).each do |key, val| %>
        <li><b><%= key %>:</b> <%= val %></li>
        <% end %>
    </ul>
</div>

<script>
    $("#show-complete").click(function() {
        $("#complete").removeClass("is-hidden");
    });
</script>

app/views/contest/upload.html.erb
<%= provide(:title, "Carica il logo di #{@contest.name}") %>

<h1 class="title">Maschera inserimento logo <%= @contest.name %></h1>
<script>
addEventListener("direct-upload:initialize", event => {
  const { target, detail } = event
  const { id, file } = detail
  target.insertAdjacentHTML("beforebegin", `
    <div id="direct-upload-${id}" class="direct-upload direct-upload--pending">
      <div id="direct-upload-progress-${id}" class="direct-upload__progress" style="width: 0%"></div>
      <span class="direct-upload__filename">${file.name}</span>
    </div>
  `)
})
 
addEventListener("direct-upload:start", event => {
  const { id } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.remove("direct-upload--pending")
})
 
addEventListener("direct-upload:progress", event => {
  const { id, progress } = event.detail
  const progressElement = document.getElementById(`direct-upload-progress-${id}`)
  progressElement.style.width = `${progress}%`
})
 
addEventListener("direct-upload:error", event => {
  event.preventDefault()
  const { id, error } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.add("direct-upload--error")
  element.setAttribute("title", error)
})
 
addEventListener("direct-upload:end", event => {
  const { id } = event.detail
  const element = document.getElementById(`direct-upload-${id}`)
  element.classList.add("direct-upload--complete")
})
</script>

<style>
  .direct-upload {
    display: inline-block;
    position: relative;
    padding: 2px 4px;
    margin: 0 3px 3px 0;
    border: 1px solid rgba(0, 0, 0, 0.3);
    border-radius: 3px;
    font-size: 11px;
    line-height: 13px;
  }
  
  .direct-upload--pending {
    opacity: 0.6;
  }
  
  .direct-upload__progress {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    opacity: 0.2;
    background: #0076ff;
    transition: width 120ms ease-out, opacity 60ms 60ms ease-in;
    transform: translate3d(0, 0, 0);
  }
  
  .direct-upload--complete .direct-upload__progress {
    opacity: 0.4;
  }
  
  .direct-upload--error {
    border-color: red;
  }
  
  input[type=file][data-direct-upload-url][disabled] {
    display: none;
  }
  </style>
  <p><%= @contest.errors.full_messages if @contest.errors.any? %></p>
  <%= form_for(@contest, url: upload_path(id: @contest.id), method: :post) do |f| %>
    <%= f.file_field :logo, multiple: false, direct_upload: true %>
    <%= f.hidden_field :id, value: @contest.id %>
    <%= f.submit 'Carica logo', class: 'button is-primary is-big' %>
  <% end %>