config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  resources :years
  root 'contest#index'
  resources :contest, only: [:show]
  resources :creators, only: [:show]
  get 'upload', to: 'contest#upload'
  post 'upload', to: 'contest#uploadpost'
  
  if ENV['WEBSIDEKIQ'] == "TRUE"
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '/numerics' do
    get 'totalphotos', to: 'numerics#totalphotos'
    get 'todayphotos', to: 'numerics#todayphotos'
    get 'totalcreators', to: 'numerics#totalcreators'
    get 'totalcreatorsapposta', to: 'numerics#totalcreatorsapposta'
    get 'todaycreatorsapposta', to: 'numerics#todaycreatorsapposta'
    get 'days', to: 'numerics#days'
    get 'photograph', to: 'numerics#photograph'
    get 'photoday', to: 'numerics#photoday'
    get 'usedonwiki', to: 'numerics#usedonwiki'
    get 'usedonwikipercentage', to: 'numerics#usedonwikipercentage'
    get 'iscrittiappostapercentage', to: 'numerics#iscrittiappostapercentage'
    get 'miglioriutenti', to: 'numerics#miglioriutenti'
    get 'iscrittiappostagraph', to: "numerics#iscrittiappostagraph"
    get 'photos_relativetogeneral', to: "numerics#photos_relativetogeneral"
    get 'participants_relativetogeneral', to: "numerics#participants_relativetogeneral"
    get 'special_photos', to: "numerics#special_photos"
    get 'new_monuments', to: "numerics#new_monuments"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :nophotos
  has_many :photos
  has_many :nophoto
  has_many :no_photo_monuments
  has_many :creators
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :set_year, only: %i[ show edit update destroy ]
  http_basic_authenticate_with name: "wikilovesmonuments", password: ENV["SECRET_PASSWORD"]


  # GET /years or /years.json
  def index
    @years = Year.all
  end

  # GET /years/1 or /years/1.json
  def show
  end

  # GET /years/new
  def new
    @year = Year.new
  end

  # GET /years/1/edit
  def edit
  end

  # POST /years or /years.json
  def create
    @year = Year.new(year_params)

    respond_to do |format|
      if @year.save
        format.html { redirect_to year_url(@year), notice: "Year was successfully created." }
        format.json { render :show, status: :created, location: @year }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /years/1 or /years/1.json
  def update
    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to year_url(@year), notice: "Year was successfully updated." }
        format.json { render :show, status: :ok, location: @year }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /years/1 or /years/1.json
  def destroy
    @year.destroy

    respond_to do |format|
      format.html { redirect_to years_url, notice: "Year was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year
      @year = Year.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def year_params
      params.require(:year).permit(:year, :storicized, :special, :special_category, :special_category_label)
    end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_form.html.erb
<%= form_with(model: year) do |form| %>
  <% if year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(year.errors.count, "error") %> prohibited this year from being saved:</h2>

      <ul>
        <% year.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :storicized %>
    <%= form.check_box :storicized %>
  </div>

  <div class="field">
    <%= form.label :special %>
    <%= form.check_box :special %>
  </div>

  <div class="field">
    <%= form.label :special_category %>
    <%= form.text_field :special_category %>
  </div>

  <div class="field">
    <%= form.label :special_category_label %>
    <%= form.text_field :special_category_label %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/years/edit.html.erb
<h1>Editing Year</h1>

<%= render 'form', year: @year %>

<%= link_to 'Show', @year %> |
<%= link_to 'Back', years_path %>

app/views/years/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Years</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Storicized</th>
      <th>Special</th>
      <th>Special category</th>
      <th>Special category label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @years.each do |year| %>
      <tr>
        <td><%= year.year %></td>
        <td><%= year.storicized %></td>
        <td><%= year.special %></td>
        <td><%= year.special_category %></td>
        <td><%= year.special_category_label %></td>
        <td><%= link_to 'Show', year %></td>
        <td><%= link_to 'Edit', edit_year_path(year) %></td>
        <td><%= link_to 'Destroy', year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Year', new_year_path %>

app/views/years/new.html.erb
<h1>New Year</h1>

<%= render 'form', year: @year %>

<%= link_to 'Back', years_path %>

app/views/years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @year.year %>
</p>

<p>
  <strong>Storicized:</strong>
  <%= @year.storicized %>
</p>

<p>
  <strong>Special:</strong>
  <%= @year.special %>
</p>

<p>
  <strong>Special category:</strong>
  <%= @year.special_category %>
</p>

<p>
  <strong>Special category label:</strong>
  <%= @year.special_category_label %>
</p>

<%= link_to 'Edit', edit_year_path(@year) %> |
<%= link_to 'Back', years_path %>